// <auto-generated />
using Business.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Business.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Business.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RestaurantAddress");

                    b.Property<string>("RestaurantName");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            RestaurantAddress = "Downtown",
                            RestaurantName = "Seerato"
                        },
                        new
                        {
                            RestaurantId = 2,
                            RestaurantAddress = "Downtown Portland",
                            RestaurantName = "Portland City Grill"
                        },
                        new
                        {
                            RestaurantId = 3,
                            RestaurantAddress = "Stark",
                            RestaurantName = "Deeny's"
                        });
                });

            modelBuilder.Entity("Business.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Blurb")
                        .HasMaxLength(255);

                    b.Property<int>("ShopId");

                    b.Property<int>("UserId");

                    b.HasKey("ReviewId");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Blurb = "Susie was AWESOME!!!! I came in last minute for a memorial service with a holiday weekend in two days. Not only did she get it done but her idea for the bunches turned out great!!!!.",
                            ShopId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ReviewId = 2,
                            Blurb = "Perfect donuts. Light and fluffy perfect evenly distributed glaze. I love just a classic glazed donut but had their apple fritter recently and it was heavenly. The coffee goes perfectly with the donuts. Great shop to hang out/work in, decent WiFi, not too loud so it's easy to focus.",
                            ShopId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ReviewId = 3,
                            Blurb = "t vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero",
                            ShopId = 3,
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 4,
                            Blurb = "Susie was AWESOME!!!! I came in last minute for a memorial service with a holiday weekend in two days. Not only did she get it done but her idea for the bunches turned out great!!!!.",
                            ShopId = 2,
                            UserId = 5
                        },
                        new
                        {
                            ReviewId = 5,
                            Blurb = "Susie was AWESOME!!!! I came in last minute for a memorial service with a holiday weekend in two days. Not only did she get it done but her idea for the bunches turned out great!!!!.",
                            ShopId = 2,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Business.Models.ReviewRestaurant", b =>
                {
                    b.Property<int>("ReviewRestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlurbRestaurant")
                        .HasMaxLength(255);

                    b.Property<int>("RestaurantId");

                    b.Property<int>("UserId");

                    b.HasKey("ReviewRestaurantId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("ReviewRestaurants");

                    b.HasData(
                        new
                        {
                            ReviewRestaurantId = 1,
                            BlurbRestaurant = "One of my favorite places to dine in Portland.  The staff, especially Fernando, who always remembers us, is extremely friendly and attentive.  I've never had less than an amazing meal here. The atmosphere is beautiful, and they have a great bar area along with outside seating and a large space for a private party.",
                            RestaurantId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ReviewRestaurantId = 2,
                            BlurbRestaurant = "We had the best server! I wish I remembered his name. The view is amazing, the food is delicious, the service is great. It is an amazing place to go. I've gone here both dressed up and more casual depending on the occasion. It's such a great place!",
                            RestaurantId = 2,
                            UserId = 3
                        },
                        new
                        {
                            ReviewRestaurantId = 3,
                            BlurbRestaurant = "I've been enjoying the food from this establishment since I was a young boy, and I'm 36yrs old now. Recently revisited them for a to-go order and couldn't be happier with the quality, quantity, or service. Canton Grill, y'all are AWESOME and I plan on being one of your customers as long as I can! Thanks :-)",
                            RestaurantId = 3,
                            UserId = 4
                        },
                        new
                        {
                            ReviewRestaurantId = 4,
                            BlurbRestaurant = "I've been enjoying the food from this establishment since I was a young boy, and I'm 36yrs old now. Recently revisited them for a to-go order and couldn't be happier with the quality, quantity, or service. Canton Grill, y'all are AWESOME and I plan on being one of your customers as long as I can! Thanks :-)",
                            RestaurantId = 3,
                            UserId = 2
                        },
                        new
                        {
                            ReviewRestaurantId = 5,
                            BlurbRestaurant = "One of my favorite places to dine in Portland.  The staff, especially Fernando, who always remembers us, is extremely friendly and attentive.  I've never had less than an amazing meal here. The atmosphere is beautiful, and they have a great bar area along with outside seating and a large space for a private party.",
                            RestaurantId = 1,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Business.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ShopAddress");

                    b.Property<string>("ShopName");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            ShopAddress = "stark",
                            ShopName = "Anna's Flower"
                        },
                        new
                        {
                            ShopId = 2,
                            ShopAddress = "164th street Vancover",
                            ShopName = "Angel's Donut and Ice Cream"
                        },
                        new
                        {
                            ShopId = 3,
                            ShopAddress = "122 ave portland 97236",
                            ShopName = "Ace Hardware"
                        });
                });

            modelBuilder.Entity("Business.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserName = "Dom"
                        },
                        new
                        {
                            UserId = 2,
                            UserName = "Jen"
                        },
                        new
                        {
                            UserId = 3,
                            UserName = "Anita"
                        },
                        new
                        {
                            UserId = 4,
                            UserName = "Devin"
                        },
                        new
                        {
                            UserId = 5,
                            UserName = "Kira"
                        });
                });

            modelBuilder.Entity("Business.Models.Review", b =>
                {
                    b.HasOne("Business.Models.Shop")
                        .WithMany("Reviews")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Business.Models.User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Models.ReviewRestaurant", b =>
                {
                    b.HasOne("Business.Models.Restaurant")
                        .WithMany("ReviewRestaurants")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
