// <auto-generated />
using Business.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Business.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Business.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RestaurantAddress");

                    b.Property<string>("RestaurantName");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            RestaurantAddress = "30th street",
                            RestaurantName = "USA"
                        },
                        new
                        {
                            RestaurantId = 2,
                            RestaurantAddress = "20th Street",
                            RestaurantName = "France"
                        },
                        new
                        {
                            RestaurantId = 3,
                            RestaurantAddress = "40th street",
                            RestaurantName = "Italy"
                        });
                });

            modelBuilder.Entity("Business.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Blurb")
                        .HasMaxLength(255);

                    b.Property<int>("ShopId");

                    b.Property<int>("UserId");

                    b.HasKey("ReviewId");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Blurb = "t vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero",
                            ShopId = 1,
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 2,
                            Blurb = "t vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero",
                            ShopId = 2,
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 3,
                            Blurb = "t vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero",
                            ShopId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Business.Models.ReviewRestaurant", b =>
                {
                    b.Property<int>("ReviewRestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlurbRestaurant")
                        .HasMaxLength(255);

                    b.Property<int>("RestaurantId");

                    b.Property<int>("UserId");

                    b.HasKey("ReviewRestaurantId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("ReviewRestaurants");

                    b.HasData(
                        new
                        {
                            ReviewRestaurantId = 1,
                            BlurbRestaurant = "t vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero",
                            RestaurantId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ReviewRestaurantId = 2,
                            BlurbRestaurant = "t vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero",
                            RestaurantId = 2,
                            UserId = 3
                        },
                        new
                        {
                            ReviewRestaurantId = 3,
                            BlurbRestaurant = "t vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero",
                            RestaurantId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Business.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ShopAddress");

                    b.Property<string>("ShopName");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            ShopAddress = "stark",
                            ShopName = "Flower"
                        },
                        new
                        {
                            ShopId = 2,
                            ShopAddress = "division",
                            ShopName = "Pet"
                        },
                        new
                        {
                            ShopId = 3,
                            ShopAddress = "Sellwoood",
                            ShopName = "Grocery"
                        });
                });

            modelBuilder.Entity("Business.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            UserName = "Dom"
                        },
                        new
                        {
                            UserId = 4,
                            UserName = "Jen"
                        },
                        new
                        {
                            UserId = 5,
                            UserName = "Anita"
                        },
                        new
                        {
                            UserId = 6,
                            UserName = "Devin"
                        });
                });

            modelBuilder.Entity("Business.Models.Review", b =>
                {
                    b.HasOne("Business.Models.Shop")
                        .WithMany("Reviews")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Business.Models.User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Business.Models.ReviewRestaurant", b =>
                {
                    b.HasOne("Business.Models.Restaurant")
                        .WithMany("ReviewRestaurants")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
